server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /api

spring:
  application:
    name: customer-service
  config:
    import: optional:configtree:/run/secrets/
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    password: ${db_password}
    username:
    url:


  kafka:
    bootstrap-servers:
    custom:
      consumer:
        customer-user:
          groupId: customer-user-group
          topic: customer-user
      producer:
        flightseat-reservation-topic: flightseat-reservation
      retry-topic-prefix: retry-
      dlq-topic-prefix: dlq-
      fatal-exceptions:
        - org.aviatrip.customerservice.exception.FatalKafkaException
        - org.springframework.kafka.support.serializer.DeserializationException
        - org.springframework.messaging.handler.annotation.support.MethodArgumentNotValidException
        - jakarta.validation.ConstraintViolationException

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    openfeign:
      okhttp:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone:

logging:
  level:
    org.apache.kafka: ERROR

ticket:
  minimal-flight-seat-reservation-duration-in-seconds: 600
  seconds-until-flight-departure-reservation-available: 4200
  seconds_until_flight_departure_reservation_available_when_pay_later_option_enabled: 7200