server:
  servlet:
    context-path: /api

spring:
  application:
    name: customer-service
  config:
    import: optional:configtree:/run/secrets/
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    password: ${db_password}
    username:
    url:

  kafka:
    #consumer:

    bootstrap-servers:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone:

kafka:
  customer-user:
    enabled: true
    main-groupId: main-customer-user-group
    main-topic: main-customer-user
    retry-groupId: retry-customer-user-group
    retry-topic: retry-customer-user
    dlq-topic: dlq-customer-user